# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'doscamarasHands.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(564, 296)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setStyleSheet("QLabel{background-color:white;}")
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.FeedLabel = QtWidgets.QLabel(Dialog)
        self.FeedLabel.setText("")
        self.FeedLabel.setObjectName("FeedLabel")
        self.verticalLayout.addWidget(self.FeedLabel)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.FeedLabel_2 = QtWidgets.QLabel(Dialog)
        self.FeedLabel_2.setText("")
        self.FeedLabel_2.setObjectName("FeedLabel_2")
        self.verticalLayout_2.addWidget(self.FeedLabel_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 2, 1, 2)
        self.CancelBTN = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CancelBTN.setFont(font)
        self.CancelBTN.setStyleSheet("QPushButton{background-color:skyblue;}\n"
"QPushButton:hover{background-color:orange;}")
        self.CancelBTN.setObjectName("CancelBTN")
        self.gridLayout.addWidget(self.CancelBTN, 1, 0, 1, 4)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Marcha4Cam - Dos Cámaras Manos"))
        self.CancelBTN.setText(_translate("Dialog", "Cerrar"))
        self.label.setText(_translate("Dialog", "Dos Cámaras Manos"))
