# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rodilla.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 700)
        Dialog.setMinimumSize(QtCore.QSize(1200, 700))
        Dialog.setStyleSheet("QLabel{background-color:white;}")
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelAnguloRodilla = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelAnguloRodilla.setFont(font)
        self.labelAnguloRodilla.setStyleSheet("QLabel{background-color:yellow;}\n"
"")
        self.labelAnguloRodilla.setObjectName("labelAnguloRodilla")
        self.verticalLayout_2.addWidget(self.labelAnguloRodilla)
        self.labelAnguloCadera = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelAnguloCadera.setFont(font)
        self.labelAnguloCadera.setStyleSheet("QLabel{background-color:red;}\n"
"")
        self.labelAnguloCadera.setObjectName("labelAnguloCadera")
        self.verticalLayout_2.addWidget(self.labelAnguloCadera)
        self.FeedLabel = QtWidgets.QLabel(Dialog)
        self.FeedLabel.setText("")
        self.FeedLabel.setObjectName("FeedLabel")
        self.verticalLayout_2.addWidget(self.FeedLabel)
        self.CancelBTN = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CancelBTN.setFont(font)
        self.CancelBTN.setStyleSheet("QPushButton{background-color:skyblue;}\n"
"QPushButton:hover{background-color:orange;}")
        self.CancelBTN.setObjectName("CancelBTN")
        self.verticalLayout_2.addWidget(self.CancelBTN)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = PlotWidget(Dialog)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 1, 0, 1, 2)
        self.graphicsCadera = PlotWidget(Dialog)
        self.graphicsCadera.setObjectName("graphicsCadera")
        self.gridLayout.addWidget(self.graphicsCadera, 3, 0, 1, 2)
        self.btnStart = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnStart.setFont(font)
        self.btnStart.setStyleSheet("QPushButton{background-color:skyblue;}\n"
"QPushButton:hover{background-color:orange;}")
        self.btnStart.setObjectName("btnStart")
        self.gridLayout.addWidget(self.btnStart, 4, 0, 1, 1)
        self.btnStop = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnStop.setFont(font)
        self.btnStop.setStyleSheet("QPushButton{background-color:skyblue;}\n"
"QPushButton:hover{background-color:orange;}\n"
"")
        self.btnStop.setObjectName("btnStop")
        self.gridLayout.addWidget(self.btnStop, 4, 1, 1, 1)
        self.labelCadera = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelCadera.setFont(font)
        self.labelCadera.setStyleSheet("QLabel{background-color:red;}")
        self.labelCadera.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCadera.setObjectName("labelCadera")
        self.gridLayout.addWidget(self.labelCadera, 2, 0, 1, 2)
        self.labelRodilla = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelRodilla.setFont(font)
        self.labelRodilla.setStyleSheet("QLabel{background-color: yellow;}")
        self.labelRodilla.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRodilla.setObjectName("labelRodilla")
        self.gridLayout.addWidget(self.labelRodilla, 0, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Marcha4Cam - Una Cámara Cuerpo"))
        self.labelAnguloRodilla.setText(_translate("Dialog", "Ángulo de la rodilla: "))
        self.labelAnguloCadera.setText(_translate("Dialog", "Ángulo de la cadera: "))
        self.CancelBTN.setText(_translate("Dialog", "Cerrar"))
        self.btnStart.setText(_translate("Dialog", "Comenzar análisis"))
        self.btnStop.setText(_translate("Dialog", "Detener análisis"))
        self.labelCadera.setText(_translate("Dialog", "Cadera"))
        self.labelRodilla.setText(_translate("Dialog", "Rodilla"))
from pyqtgraph import PlotWidget
